# Generated by Django 2.2.28 on 2022-09-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('schoolname', models.CharField(max_length=255)),
                ('allowAddMember', models.CharField(max_length=255)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('allowDisplay', models.CharField(max_length=20)),
                ('allowEdit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foldername', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfUsers', models.IntegerField()),
                ('permissions', models.CharField(max_length=100)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Class')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.User')),
            ],
        ),
        migrations.CreateModel(
            name='FolderInClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfFolder', models.IntegerField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Class')),
                ('FolderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.User'),
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('defindName', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('learned', models.CharField(max_length=20)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfCourse', models.IntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Course')),
                ('folderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numberOfCourse', models.IntegerField()),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Class')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizlet_API.User'),
        ),
    ]
