# Generated by Django 4.0.6 on 2022-09-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0003_alter_course_description_alter_folder_description'),
        ('Quizlet_API', '0004_alter_user_first_name'),
    ]

    operations = [
    ]
