# Generated by Django 4.0.6 on 2022-09-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0005_merge_20220909_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
