# Generated by Django 4.0.6 on 2022-09-12 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0007_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(through='Quizlet_API.UserInClass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinclass',
            name='numberOfUsers',
            field=models.IntegerField(default=0),
        ),
    ]
