# Generated by Django 4.0.6 on 2022-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0011_alter_courseinclass_numberofcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinclass',
            name='numberOfCourse',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
