# Generated by Django 4.0.6 on 2022-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0012_alter_courseinclass_numberofcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinclass',
            name='permissions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
