# Generated by Django 4.0.6 on 2022-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0013_alter_userinclass_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinclass',
            name='permissions',
            field=models.CharField(max_length=100),
        ),
    ]
