# Generated by Django 4.0.6 on 2022-09-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='allowAddMember',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
