# Generated by Django 4.0.6 on 2022-09-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0016_alter_class_allowaddmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfolder',
            name='numberOfCourse',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='folderinclass',
            name='numberOfFolder',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
