# Generated by Django 4.0.6 on 2022-09-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0017_alter_courseinfolder_numberofcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(through='Quizlet_API.CourseInClass', to='Quizlet_API.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='folders',
            field=models.ManyToManyField(through='Quizlet_API.FolderInClass', to='Quizlet_API.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='courses',
            field=models.ManyToManyField(through='Quizlet_API.CourseInFolder', to='Quizlet_API.course'),
        ),
    ]
