# Generated by Django 4.0.6 on 2022-09-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0018_class_courses_class_folders_folder_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinclass',
            name='permissions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
