# Generated by Django 4.0.6 on 2022-10-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0019_alter_userinclass_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
