# Generated by Django 4.0.6 on 2022-11-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0020_alter_flashcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='numberFlashcard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='learned',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='folder',
            name='courses',
            field=models.ManyToManyField(null=True, through='Quizlet_API.CourseInFolder', to='Quizlet_API.course'),
        ),
    ]
