# Generated by Django 4.0.6 on 2022-10-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizlet_API', '0020_alter_flashcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='learned',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
